web_project/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns=[
    path('logout/',views.user_logout,name='logout'),
    path("<int:pk>",views.UpdateUer.as_view(),name="update"),
]

web_project/blogs/urls.py
from django.urls import path
from . import views

app_name='blogs'

urlpatterns=[
    path('createblog/', views.CreateBlog.as_view(), name='create'),
    path('edit/<int:pk>', views.EditBlog.as_view(), name='edit'),
    path('<int:pk>/', views.BlogDetails.as_view(), name="details"),
    path('delete/<int:pk>', views.DeleteBlog.as_view(), name="delete"),
    path('home/', views.HomePage.as_view(), name="homepage"),
    path('<username>', views.Uerblogs.as_view(), name='uerblogs'),
    path("explore/", views.ExploreBlogs.as_view(), name="explore"),
    path('yay/', views.yay, name="yay"),
    path('unyay/', views.unyay, name="unyay"),
    path('nay/', views.nay, name="nay"),
    path("unnay/", views.unnay, name="unnay"),

]

web_project/categories/urls.py
from django.urls import path
from . import views

app_name='categories'

urlpatterns=[
    path('<slug>',views.Categoryblogs.as_view(),name="category_blogs"),
    path('subscribe/<name>',views.Subscribe,name="subscribe"),
    path('unsubscribe/<name>',views.Unsubscribe,name="unsubscribe"),
    path("cat_list/",views.CategoryList.as_view(),name="list"),
]

web_project/web_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views as v
from accounts import views
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

handler404 = 'my_app.views.handler404'
handler500 = 'my_app.views.handler500'

urlpatterns = [
    path('',views.Home,name="Home"),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('blogs/',include('blogs.urls',namespace='blogs')),
    path('categories/',include('categories.urls',namespace='categoires')),
    path(r'auth/', include('social_django.urls', namespace='social')),  # <- Here


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_project/categories/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from accounts.models import Uer

User = get_user_model()
# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=25,unique=True)
    info=models.TextField(max_length=255,blank=True,default="")
    slug = models.SlugField(allow_unicode=True, unique=True)
    # Members=models.ManyToManyField(User,related_name="members")
    pic=models.ImageField(upload_to="categories_photos" ,null=True)
    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):

        self.slug = slugify(self.name)
        super().save()

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})

class Subscriber(models.Model):
    member=models.ForeignKey(User,related_name="member",on_delete=models.CASCADE)
    category=models.ForeignKey("Category",related_name="category",on_delete=models.CASCADE)

    def __str__(self):
        return "{} subscribed to {}".format(self.member.username,self.category)

    class Meta():
        unique_together=("member","category")

web_project/categories/views.py
from django.shortcuts import render
from .models import Category,Subscriber
from blogs import models as m
from django.http import Http404
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.urls import reverse_lazy
from django.http import ( HttpResponseRedirect,
                          HttpResponse,
                          JsonResponse,
                          )

# Create your views here.
class CategoryList(LoginRequiredMixin, generic.ListView):

    model = Category
    template_name = "categories/cat_list.html"
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        try:
            subscribed = Subscriber.objects.raw("SELECT id,category_id from categories_subscriber where member_id = %s",[self.request.user.id])
            subbed_categories=[]
            for sub in subscribed:
                subbed_categories.append(sub.category_id)
                print(sub.id)
            self.subbed_cats = Category.objects.filter(id__in=subbed_categories)
            print(self.subbed_cats)
            context["subbed_cats"]=self.subbed_cats
            return context
        except:
            return context

class Categoryblogs(LoginRequiredMixin, generic.ListView):

    model=m.Blog
    template_name="categories/category_blogs.html"

    def get_queryset(self):
        try:
            self.blog_category = Category.objects.prefetch_related("cat_blogs").get(
                name__iexact=self.kwargs.get("slug")
            )
            name=slugify(self.kwargs.get("slug"))
            category = Category.objects.get(slug=name)
            subscribed = Subscriber.objects.raw("SELECT id From categories_subscriber where member_id=%s and category_id=%s",[self.request.user.id,category.id])
            # for s in subscribed:
            #     self.subscribed=s
            if len(subscribed) == 1:
                self.is_subscribed = subscribed[0]
            else:
                self.is_subscribed = None
            self.trending = self.blog_category.cat_blogs.order_by("points")

            yayed_blogs = self.request.user.yays.all()
            self.y_blogs=[]
            for yay in yayed_blogs:
                print(yay.yayed.id)
                self.y_blogs.append(yay.yayed.id)
            print("stage 1")
            nayed_blogs = self.request.user.nays.all()
            self.n_blogs=[]
            for nay in nayed_blogs:
                self.n_blogs.append(nay.nayed.id)

        except Category.DoesNotExist:
            raise Http404
        else:
            return self.blog_category.cat_blogs.order_by("-time_written")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            subscribed = Subscriber.objects.raw("SELECT id,category_id from categories_subscriber where member_id = %s",[self.request.user.id])
            subbed_categories=[]
            for sub in subscribed:
                subbed_categories.append(sub.category_id)
                print(sub.id)
            self.subbed_cats = Category.objects.filter(id__in=subbed_categories)
            print(self.subbed_cats)
            context["subbed_cats"]=self.subbed_cats
        except:
            pass
        context["cat"] = self.blog_category
        context["is_subscribed"] = self.is_subscribed
        context["trending"] = self.trending
        context["yayed_blogs"] = self.y_blogs
        context["nayed_blogs"] = self.n_blogs
        return context

@login_required
def Subscribe(request,name):

    subbed=Subscriber()
    subbed.member=request.user
    cat_name=slugify(name)
    subbed.category=Category.objects.get(slug=cat_name)
    subbed.save()

    return HttpResponseRedirect(reverse_lazy("categories:category_blogs",kwargs={"slug":cat_name}))

@login_required
def Unsubscribe(request,name):

    cat_name=slugify(name)
    category=Category.objects.get(slug=cat_name)
    subbed=Subscriber.objects.get(member=request.user,category=category)
    subbed.delete()

    return HttpResponseRedirect(reverse_lazy("categories:category_blogs",kwargs={"slug":cat_name}))

web_project/categories/templates/categories/2.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
      <meta charset="utf-8">
      <title> U </title>

      {# JQuery #}
      <script
			  src="https://code.jquery.com/jquery-3.4.0.js"
			  integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo="
			  crossorigin="anonymous"></script>

      {# Medium Style Editor #}
      {# <link rel="stylesheet" href="{% static 'medium/css/themes/beagle.css' %}"> #}
      <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/themes/beagle.css" type="text/css" media="screen" charset="utf-8">
      <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>

      {# Custom CSS #}
      <link rel="stylesheet" href="{% static 'css/blog_base_master.css' %}">

      {# Background Color #}
      {% block color %}   {% endblock %}

      </script>

      {# Bootstrap #}
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      {# <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> #}
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      {# Google Fonts #}
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,800" rel="stylesheet">

      {# Font Awesome #}
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body class="bodyz">

    <nav class="navbar navbar-expand-lg  navbar-dark bg-dark fixed-top">
      {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'blogs:homepage' %}">U</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blogs:homepage' %}">Home <span class="sr-only">{% block homepage_location %}{% endblock %}</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogs:explore' %}">Explore</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'categories:list' %}">Categories</a>
            </li>
            {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="http://127.0.0.1/U-Blogging-website/web_project/php/controlpanel/">ControlPanel</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
              <a  class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Subscription
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                {% for cat in subbed_cats %}
                  <a class="dropdown-item" href="{% url 'categories:category_blogs' slug=cat.slug %}">{{cat.name}}</a>
                {% endfor %}
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogs:uerblogs' username=user.username %}">My Account</a>
            </li>
          </ul>
        </div>
        <form class="form-inline d-flex justify-content-end">
          <a class="btn btn-sm btn-outline-secondary" href="{% url 'blogs:create' %}">New post</a>
          <a class="btn btn-sm btn-outline-secondary" href="{% url 'accounts:logout' %}">Logout</a>
        </form>
        {% else %}
        <a class="navbar-brand" href="#">U</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogs:explore' %}">Explore</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'categories:list' %}">Categories</a>
            </li>

            <li class="nav-item dropdown">
              <a  class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Art</a>
                <a class="dropdown-item" href="#">Tech</a>
                <a class="dropdown-item" href="#">Food</a>
                <a class="dropdown-item" href="#">plapla</a>
                <a class="dropdown-item" href="#">plaplapla</a>
                <a class="dropdown-item" href="#">plaplaplapla</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">My A ccount</a>
            </li>

                    <form class="form-inline">
                      <button class="btn btn-sm btn-outline-secondary" type="button">New post</button>
                      <button class="btn btn-sm btn-outline-secondary" type="button">Logout</button>
                    </form>
          </ul>
        </div>
        {% endif %}
      </nav>
{% block content %}

{% endblock %}

  </body>
</html>

web_project/categories/templates/categories/cat_list.html
{% extends "categories/category_base.html" %}

{% block content %}


<style media="screen">
  .card {
  /* Add shadows to create the "card" effect */
  box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
  transition: 0.3s;
}

/* On mouse-over, add a deeper shadow */
.card:hover {
  box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

/* Add some padding inside the card container */
.container {
  padding: 2px 16px;
}
</style>

<div class="container" >
  <div class="row" >

        {% for cat in category_list %}


        <div style=" "class="col-4 my-2" id="{{cat.id}}">



              <div class="card">
           <img  style="
           border:none;
           width:100%;
           height:14rem;
           background-image:
linear-gradient(to bottom, rgba(245, 246, 252, 0.52), rgba(40, 176, 70, 0.23)),
url({{cat.pic.url}});
background-position:center;
    background-size:contain;

           ">
           <div class="container">
    <center>      <a href="{% url 'categories:category_blogs' slug=cat.slug %}" > <h4><b>{{cat.name}}</b></h4></a>   </center>
           </div>
         </div>




        </div>
        {% endfor %}
    </div>
  </div>

{% endblock %}

web_project/categories/templates/categories/category_base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
      <meta charset="utf-8">
      <title> U </title>



      <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">

      {# JQuery #}
      <script
			  src="https://code.jquery.com/jquery-3.4.0.js"
			  integrity="sha256-DYZMCC8HTC+QDr5QNaIcfR7VSPtcISykd+6eSmBW5qo="
			  crossorigin="anonymous"></script>

      {# Medium Style Editor #}
      {# <link rel="stylesheet" href="{% static 'medium/css/themes/beagle.css' %}"> #}
      <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/css/themes/beagle.css" type="text/css" media="screen" charset="utf-8">
      <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>

      {# Custom CSS #}
      <link rel="stylesheet" href="{% static 'css/blog_base_master.css' %}">

      {# Background Color #}
      {% block color %}  {% endblock %}

      </script>

      {# Bootstrap #}
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      {# <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> #}
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      {# Google Fonts #}
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,800" rel="stylesheet">

      {# Font Awesome #}
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <style media="screen">
  a:link {
    text-decoration: none;
    color:#28a745;
  }
  a{
    color:#28a745;

  }
  a:hover {
    color:#000;
}
  </style>
  <body>

    <link href="https://fonts.googleapis.com/css?family=Work+Sans&display=swap" rel="stylesheet">

<div class="container">

    <nav class="navbar navbar-expand-lg"  style=" font-family: 'Montserrat', sans-serif;  ">

      </style>
      {% if user.is_authenticated %}
        <a class="navbar-brand" href="{% url 'blogs:homepage' %}"><h1 style="

    font-family: 'Work Sans', sans-serif;  font-weight:bold;">U</h1></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blogs:homepage' %}">Home <span class="sr-only">{% block homepage_location %}{% endblock %}</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogs:explore' %}">Explore</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'categories:list' %}">Categories</a>
            </li>
            {% if user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="http://127.0.0.1/U-Blogging-website/web_project/php/controlpanel/">ControlPanel</a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
              <a  class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Subscription
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                {% for cat in subbed_cats %}
                  <a class="dropdown-item" href="{% url 'categories:category_blogs' slug=cat.slug %}">{{cat.name}}</a>
                {% endfor %}
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogs:uerblogs' username=user.username %}">My Account</a>
            </li>

          </ul>
        </div>


                <form class="form-inline d-flex justify-content-end" style="height:120$;">

                  <a class="btn btn-sm  btn-outline-success" href="{% url 'blogs:create' %}">New post</a>
                  <a class="btn btn-sm  btn-outline-success" href="{% url 'accounts:logout' %}">Logout</a>

                </form>



        {% else %}
        <a class="navbar-brand" href="#">U</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Explore</a>
            </li>

            <li class="nav-item dropdown">
              <a  class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                categories
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Art</a>
                <a class="dropdown-item" href="#">Tech</a>
                <a class="dropdown-item" href="#">Food</a>
                <a class="dropdown-item" href="#">plapla</a>
                <a class="dropdown-item" href="#">plaplapla</a>
                <a class="dropdown-item" href="#">plaplaplapla</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">My A ccount</a>
            </li>

                    <form class="form-inline">
                      <button class="btn btn-sm btn-outline-secondary" type="button">New post</button>
                      <button class="btn btn-sm btn-outline-secondary" type="button">Logout</button>
                    </form>
          </ul>
        </div>
        {% endif %}
      </nav>

</div>


{% block content %}

{% endblock %}
  </body>
</html>

web_project/categories/templates/categories/category_blogs.html
{% extends "categories/category_base.html" %}

{% load static %}

{% block color %}
  <link rel="stylesheet" href="{% static "css/grey.css" %}">
{% endblock %}

{% block content %}

<div class="container">

      <div class="Profile_Info p-5" >
          <div class="row">

              <div  class="col-2">
                {% if cat.pic %}
    <img style="width:10rem; height:10rem; border-radius:50%;"src="{{cat.pic.url}}" alt="">
                {% else %}
                <img style="" src="{% static "css/uicon.png" %}" alt="">
                {% endif %}
                <center><h2>{{cat.name}}</h2></center>
              </div>




<div class="col-1">

</div>
              <div style="margin-top:auto; margin-bottom:auto;" class="col-6">
                <p>{{cat.info}}</p>
                </div>

                <div class="col-1">

                </div>


                <div style="margin-top:auto; margin-bottom:auto;" class="col-2">
                {% if is_subscribed %}
                  <div class="sub-unsub">
                    <a href="{% url 'categories:unsubscribe' name=cat.slug %}" class="unsub-btn  p-2">Subscribed</a>
                  </div>
                  {% else %}
                  <div class="sub-unsub">
                    <a href="{% url 'categories:subscribe' name=cat.slug %}" class="sub-btn p-2">Subscribe</a>
                  </div>
                {% endif %}
              </div>


          </div>
</div>
      <div class="container">
        <div class="row">

      <div class="col-md-8 col-sm-12 " style="margin-top:3vh;">
        {% for blog in blog_list %}
          {% include "blogs/_blog.html" %}
        {% endfor %}
      </div>
      <div  style="margin-top:2vh;" class="col-md-4 col-sm-0" >
        {% if trending.count > 2 %}
          {% for blog in trending|slice:":3" %}
          <div class="mycard card" style="width: 100%; height:25vh;">
            <div class="card-body">
              <h5 style="font-size:1em;" class="card-title">{{blog.title}}</h5>
              <h6 class="card-subtitle mb-2"  style="font-size:0.7em;opacity:0.9; color:white;">{{blog.time_written|timesince}}</h6>
              <p class="card-text" style="font-size:0.7em;">{{blog.content|striptags|safe|truncatechars_html:100}}</p>
            </div>
            <a  style="  margin-left:20px;margin-bottom:20px; color:white; "  href="{% url 'blogs:details' pk=blog.pk %}" class="card-link">See more</a>

          </div>
          {% endfor %}
        {% else %}
          {% for blog in trending %}
          <div class="mycard card " style="width: 100%; height:25vh;">
            <div class="card-body">
              <h5 style="font-size:1em;" lass="card-title">{{blog.title}}</h5>
              <h6 class="card-subtitle mb-2   " style="font-size:0.7em;opacity:0.9; color:white;" >{{blog.time_written|timesince}}</h6>
              <p class="card-text" style="font-size:0.7em;" >{{blog.content|striptags|safe|truncatechars_html:80}}</p>
            </div>
            <a style="  margin-left:20px;margin-bottom:20px; color:white; " href="{% url 'blogs:details' pk=blog.pk %}" class="card-link">See more</a>

          </div>
          {% endfor %}
        {% endif %}
    </div>
  </div>
</div>


<script type="text/javascript">
    sub_btn=$(".sub-btn")
    unsub_btn=$(".unsub-btn")

    sub_btn.mouseenter(function(event){
      sub_btn.css('color',"white")
      sub_btn.css("background-color","#28a745")

    })

    sub_btn.mouseleave(function(event){
      sub_btn.css('color',"#28a745")
      sub_btn.css("background-color","white")
    })

    unsub_btn.mouseenter(function(event){
      unsub_btn.css('color',"white")
      unsub_btn.css("background-color","#28a745")
      unsub_btn.text("Unsubscribe")
    })

    unsub_btn.mouseleave(function(event){
      unsub_btn.css('color',"#0000EE")
      unsub_btn.css("background-color","white")
      unsub_btn.text("Subscribed")
    })

</script>
{% endblock %}