web_project/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns=[
    path('logout/',views.user_logout,name='logout'),
    path("<int:pk>",views.UpdateUer.as_view(),name="update"),
]

web_project/blogs/urls.py
from django.urls import path
from . import views

app_name='blogs'

urlpatterns=[
    path('createblog/', views.CreateBlog.as_view(), name='create'),
    path('edit/<int:pk>', views.EditBlog.as_view(), name='edit'),
    path('<int:pk>/', views.BlogDetails.as_view(), name="details"),
    path('delete/<int:pk>', views.DeleteBlog.as_view(), name="delete"),
    path('home/', views.HomePage.as_view(), name="homepage"),
    path('<username>', views.Uerblogs.as_view(), name='uerblogs'),
    path("explore/", views.ExploreBlogs.as_view(), name="explore"),
    path('yay/', views.yay, name="yay"),
    path('unyay/', views.unyay, name="unyay"),
    path('nay/', views.nay, name="nay"),
    path("unnay/", views.unnay, name="unnay"),

]

web_project/categories/urls.py
from django.urls import path
from . import views

app_name='categories'

urlpatterns=[
    path('<slug>',views.Categoryblogs.as_view(),name="category_blogs"),
    path('subscribe/<name>',views.Subscribe,name="subscribe"),
    path('unsubscribe/<name>',views.Unsubscribe,name="unsubscribe"),
    path("cat_list/",views.CategoryList.as_view(),name="list"),
]

web_project/web_project/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views as v
from accounts import views
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

handler404 = 'my_app.views.handler404'
handler500 = 'my_app.views.handler500'

urlpatterns = [
    path('',views.Home,name="Home"),
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('blogs/',include('blogs.urls',namespace='blogs')),
    path('categories/',include('categories.urls',namespace='categoires')),
    path(r'auth/', include('social_django.urls', namespace='social')),  # <- Here


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_project/blogs/models.py
from django.db import models
# from django.db.models import property

from categories.models import Category
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.http import HttpResponseRedirect,HttpResponse

User = get_user_model()
# Create your models here.

class Blog(models.Model):

    points=models.IntegerField(default=0)
    title=models.CharField(max_length=255, unique=False, blank=True, default="")
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name="blogs")
    category=models.ForeignKey(Category,on_delete=models.CASCADE,related_name="cat_blogs")
    time_written=models.DateTimeField(auto_now=True)
    # images=models.ManyToManyField('Image',related_name="blog_images")
    # yays=models.ManyToManyField('Yay',related_name="post_yays")
    # nays=models.ManyToManyField('Nay',related_name="post_nays")
    # comments=models.ManyToManyField('Comment',related_name="post_comments")
    content=models.TextField()
    # photo=models.ImageField(upload_to="images/")

    def __str__(self):
        return "{} by {}".format(self.title,self.author)

    def get_absolute_url(self):
        return reverse('blogs:details',args=[self.id])

class Image(models.Model):

    post=models.ForeignKey(Blog,on_delete=models.CASCADE,related_name="blog_images")
#for some reason its refusing to take the title of the post
    img=models.ImageField(upload_to="images/")

class Yay(models.Model):

    yayer=models.ForeignKey(User,on_delete=models.CASCADE,related_name="yays")
    yayed=models.ForeignKey(Blog,on_delete=models.CASCADE,related_name="blog_yays")

    def save(self,*args,**kwargs):

        self.yayed.points = self.yayed.points + 1
        self.yayed.save()
        super().save()

    def delete(self,*args,**kwargs):

        self.yayed.points = self.yayed.points - 1
        self.yayed.save()
        super().delete()

    def __str__(self):
        return "{} yayed {}".format(self.yayer.username,self.yayed.title)

    class Meta:
        unique_together=("yayer","yayed")

class Nay(models.Model):

    nayer=models.ForeignKey(User,on_delete=models.CASCADE,related_name="nays")
    nayed=models.ForeignKey(Blog,on_delete=models.CASCADE,related_name="blog_nays")

    def save(self,*args,**kwargs):

        self.nayed.points = self.nayed.points - 1;
        self.nayed.save()
        super().save()

    def delete(self,*args,**kwargs):

        self.nayed.points = self.nayed.points + 1;
        self.nayed.save()
        super().delete()

    def __str__(self):
            return "{} nayed {}".format(self.nayer.username,self.nayed.title)

    class Meta:
        unique_together=("nayer","nayed")
class Comment(models.Model):

    author=models.ForeignKey(User,on_delete=models.CASCADE)#may cause the comment to be poseted by the active user
    post=models.ForeignKey(Blog,on_delete=models.CASCADE,related_name="blog_comments")
    content=models.TextField(max_length=280)

    def __str__(self):
        return "comment by {}".format(self.author.username)

web_project/blogs/forms.py
from django import forms
from .models import Blog,Comment


class BlogForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].widget.attrs.update({'class': 'special'})
    class Meta:
        model=Blog
        fields={
                'title',
                'content',
                'category',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'content': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }

class EditBlogForm(forms.ModelForm):

    class Meta:
        model=Blog
        fields={
            'title',
            'content',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'content': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }

web_project/blogs/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import ( HttpResponseRedirect,
                          HttpResponse,
                          JsonResponse,
                          )
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import forms
from . import models
from categories.models import Category,Subscriber
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.

# ----class based view----
from django import template
from django.utils.safestring import mark_safe
from django.template.defaultfilters import stringfilter
from django.utils.text import normalize_newlines

register = template.Library()

def remove_newlines(text):
    """
    Removes all newline characters from a block of text.
    """
    # First normalize the newlines using Django's nifty utility
    normalized_text = normalize_newlines(text)
    # Then simply remove the newlines like so.
    return mark_safe(normalized_text.replace('\n', ' '))
remove_newlines.is_safe = True
remove_newlines = stringfilter(remove_newlines)
register.filter(remove_newlines)




class CreateBlog(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):

    form_class=forms.BlogForm
    template_name='blogs/blog_form.html'

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        try:
            subscribed = Subscriber.objects.raw("SELECT id,category_id from categories_subscriber where member_id = %s",[self.request.user.id])
            subbed_categories=[]
            for sub in subscribed:
                subbed_categories.append(sub.category_id)
                print(sub.id)
            self.subbed_cats = Category.objects.filter(id__in=subbed_categories)
            print(self.subbed_cats)
            context["subbed_cats"]=self.subbed_cats
            return context
        except:
            return context
    def form_valid(self,form):

        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()

        for file in self.request.FILES:
            image=models.Image()
            image.img = self.request.FILES[file]
            image.post  = self.object
            image.save()

        return super().form_valid(form)

class EditBlog(LoginRequiredMixin, generic.UpdateView):
    model=models.Blog
    form_class=forms.EditBlogForm
    template_name="blogs/edit_blog.html"

    def form_valid(self,form):

        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()

        for file in self.request.FILES:
            image=models.Image()
            image.img=self.request.FILES[file]
            image.post=self.object
            image.save()

        return super().form_valid(form)
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        try:
            subscribed = Subscriber.objects.raw("SELECT id,category_id from categories_subscriber where member_id = %s",[self.request.user.id])
            subbed_categories=[]
            for sub in subscribed:
                subbed_categories.append(sub.category_id)
                print(sub.id)
            self.subbed_cats = Category.objects.filter(id__in=subbed_categories)
            print(self.subbed_cats)
            context["subbed_cats"]=self.subbed_cats
            return context
        except:
            return context

class BlogDetails(LoginRequiredMixin, generic.DetailView ):

    model=models.Blog
    template_name="blogs/blog_details.html"

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        try:
            subscribed = Subscriber.objects.raw("SELECT id,category_id from categories_subscriber where member_id = %s",[self.request.user.id])
            subbed_categories=[]
            for sub in subscribed:
                subbed_categories.append(sub.category_id)
                print(sub.id)
            self.subbed_cats = Category.objects.filter(id__in=subbed_categories)
            print(self.subbed_cats)
            context["subbed_cats"]=self.subbed_cats
            return context
        except:
            return context

class DeleteBlog(LoginRequiredMixin, generic.DeleteView):

    model=models.Blog
    template_name="blogs/bye_blog.html"

    def get_success_url(self):
        return reverse_lazy("blogs:homepage")

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        try:
            subscribed = Subscriber.objects.raw("SELECT id,category_id from categories_subscriber where member_id = %s",[self.request.user.id])
            subbed_categories=[]
            for sub in subscribed:
                subbed_categories.append(sub.category_id)
                print(sub.id)
            self.subbed_cats = Category.objects.filter(id__in=subbed_categories)
            print(self.subbed_cats)
            context["subbed_cats"]=self.subbed_cats
            return context
        except:
            return context

class Uerblogs(LoginRequiredMixin, generic.ListView):

    model=models.Blog
    template_name="blogs/user_posts.html"

    def get_queryset(self):
        try:
            self.blog_user = User.objects.prefetch_related("blogs").get(
                username__iexact=self.kwargs.get("username")
            )
            self.trending = self.blog_user.blogs.order_by("points")

            yayed_blogs = self.request.user.yays.all()
            self.y_blogs=[]
            for yay in yayed_blogs:
                print(yay.yayed.id)
                self.y_blogs.append(yay.yayed.id)

            nayed_blogs = self.request.user.nays.all()
            self.n_blogs=[]
            for nay in nayed_blogs:
                self.n_blogs.append(nay.nayed.id)
        except User.DoesNotExist:
            raise Http404
        else:
            return self.blog_user.blogs.all().order_by("-time_written")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            subscribed = Subscriber.objects.raw("SELECT id,category_id from categories_subscriber where member_id = %s",[self.request.user.id])
            subbed_categories=[]
            for sub in subscribed:
                subbed_categories.append(sub.category_id)
                print(sub.id)
            self.subbed_cats = Category.objects.filter(id__in=subbed_categories)
            print(self.subbed_cats)
            context["subbed_cats"]=self.subbed_cats
        except:
            pass
        context["blog_user"] = self.blog_user
        context["trending"]  = self.trending
        context["yayed_blogs"] = self.y_blogs
        context["nayed_blogs"] = self.n_blogs
        return context

class HomePage(LoginRequiredMixin, generic.ListView):

    model=models.Blog
    template_name = "blogs/home.html"

    def get_queryset(self):
        try:
            cats=[]
            i=0
            categories = Subscriber.objects.raw("select id,category_id FROM categories_subscriber WHERE member_id=%s",[self.request.user.id])
            for cat in categories:
                cats.append(cat.category)
            print(cats)
            self.blogs=models.Blog.objects.filter(category__in=cats).order_by("-time_written")
            self.trending=models.Blog.objects.order_by("points")

            yayed_blogs = self.request.user.yays.all()
            self.y_blogs=[]
            for yay in yayed_blogs:
                print(yay.yayed.id)
                self.y_blogs.append(yay.yayed.id)
            print("stage 1")
            nayed_blogs = self.request.user.nays.all()
            self.n_blogs=[]
            for nay in nayed_blogs:
                self.n_blogs.append(nay.nayed.id)

        except User.DoesNotExist:
            raise Http404
        return self.blogs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            subscribed = Subscriber.objects.raw("SELECT id,category_id from categories_subscriber where member_id = %s",[self.request.user.id])
            subbed_categories=[]
            for sub in subscribed:
                subbed_categories.append(sub.category_id)
                print(sub.id)
            self.subbed_cats = Category.objects.filter(id__in=subbed_categories)
            print(self.subbed_cats)
            context["subbed_cats"]=self.subbed_cats
        except:
            pass
        context["blogs"] = self.blogs
        context["trending"]=self.trending
        context["yayed_blogs"] = self.y_blogs
        context["nayed_blogs"] = self.n_blogs
        return context

class ExploreBlogs(LoginRequiredMixin, generic.ListView):

    model=models.Blog
    template_name = "blogs/explore.html"

    def get_queryset(self):
        try:
            cats=[]
            i=0
            categories = Subscriber.objects.raw("select id,category_id FROM categories_subscriber WHERE member_id=%s",[self.request.user.id])

            for cat in categories:
                cats.append(cat.category)

            self.blogs = models.Blog.objects.exclude(category__in=cats).order_by("-time_written")
            self.trending = models.Blog.objects.order_by("points")

            yayed_blogs = self.request.user.yays.all()
            self.y_blogs=[]
            for yay in yayed_blogs:
                print(yay.yayed.id)
                self.y_blogs.append(yay.yayed.id)

            nayed_blogs = self.request.user.nays.all()
            self.n_blogs=[]
            for nay in nayed_blogs:
                self.n_blogs.append(nay.nayed.id)

        except User.DoesNotExist:
            raise Http404
        return self.blogs

    def get_context_data(self, **kwargs):

web_project/blogs/templates/blogs/_blog.html
{% load static %}

{# JS #}
<script type="text/javascript">

  function yay(event){
    id=$(event.target).attr("id").split("_")[0]
    console.log("yayed "+id);
    $.ajax({
        url:'{% url "blogs:yay" %}',
        method : "GET",
        data : {
          "pk":id,
        },
        success : function(data){
          $(event.target).css("color","orange")
          $(event.target).unbind("click")
          $(event.target).click(unyay)
          $("#"+id+"_nay").css("color","black")
          $("#"+id+"_nay").unbind("click")
          $("#"+id+"_nay").click(nay)
          console.log(event.target)
          console.log(data)
          $("#"+id+"_points").text(data)
        },
    })
  }

  function unyay(event){

    id=$(event.target).attr("id").split("_")[0]
    console.log("unyayed "+id);
    $.ajax({
        url:'{% url "blogs:unyay"%}',
        method : "GET",
        data : {
          "pk":id,
        },
        success : function(data){
          $(event.target).css("color","black")
          $(event.target).unbind("click")
          $(event.target).click(yay)
          console.log(event.target)
          console.log(data)
          $("#"+id+"_points").text(data)

        },
    })
  }

  function nay(event){

    console.log($(event.target).attr("id"));
    id=$(event.target).attr("id").split("_")[0]
    console.log("nayed "+id);
    $.ajax({
        url:'{% url "blogs:nay" %}',
        method : "GET",
        data : {
          "pk":id,
        },
        success : function(data){
          console.log("in");
          $(event.target).css("color","blue")
          $(event.target).unbind("click")
          $(event.target).click(unnay)
          $("#"+id+"_yay").css("color","black")
          $("#"+id+"_yay").unbind("click")
          $("#"+id+"_yay").click(yay)
          console.log(event.target)
          console.log(data)
          $("#"+id+"_points").text(data)

        },
    })
  }

  function unnay(event){

    id=$(event.target).attr("id").split("_")[0]
    console.log("unnayed "+id);
    $.ajax({
        url:'{% url "blogs:unnay" %}',
        method : "GET",
        data : {
          "pk":id,
        },
        success : function(data){
          $(event.target).css("color","black")
          $(event.target).unbind("click")
          $(event.target).click(nay)
          console.log(event.target)
          console.log(data)
          $("#"+id+"_points").text(data)


        },
    })
  }

</script>

<link href="https://fonts.googleapis.com/css?family=B612+Mono&display=swap" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

<div style="border-left:2px solid #28a745; margin-top:0px; margin-bottom:20px;
" class="post-card card ">
  <div class="card-body">
    <span style="

    font-family: 'B612 Mono', monospace; font-weight:bold; font-size:1.1em; color:#28a745;"> {{blog.title}}</span>
<br>
  <a href="{% url 'categories:category_blogs' slug=blog.category.slug %}">
    {% if blog.author.uer.profile_pic %}
    <img style="width:30px; height:30px;   border-Radius:100%;"class="writer"src="{{blog.author.uer.profile_pic.url}}" alt="">
    {% else %}
    <img class="writer" src="{% static "css/uicon.png" %}" alt="">
    {% endif %}
    {{blog.category.name}}
  </a>

  <span style="font-family: 'Open Sans', sans-serif; font-weight:lighter; font-size:0.8em;">
    Posted by <a href="{% url 'blogs:uerblogs' username=blog.author.username %}"
                 class="username-anchor"
    >u/{{blog.author.username}}</a> {{blog.time_written|timesince}}
  </span>
<div class="row">
  <div class="col-1" style="margin-top:auto;margin-bottom:auto;">
    <span style="float:right;font-size:1.4em;">

      <i class="far fa-thumbs-up"  id="{{blog.id}}_yay"></i>
      <br>
      <span style="color:grey; font-size:0.7em;" id="{{blog.id}}_points">{{blog.points}}</span>
      <br>
      <i class="far fa-thumbs-down"  id="{{blog.id}}_nay"></i>
    </span>


        {% if blog.id in yayed_blogs %}
        <script type="text/javascript">
          console.log("yayed");
          $("#{{blog.id}}_yay").css("color",'orange')
          $("#{{blog.id}}_yay").click(unyay)
        </script>
        {% else %}
        <script type="text/javascript">
          console.log("not yayed")
          $("#{{blog.id}}_yay").css("color",'black')
          $("#{{blog.id}}_yay").click(yay)
        </script>
        {% endif %}

         {% if blog.id in nayed_blogs %}
         <script type="text/javascript">
            console.log("nayed");
           $("#{{blog.id}}_nay").css("color","blue")
           $("#{{blog.id}}_nay").click(unnay)
         </script>
         {% else %}
         <script type="text/javascript">
            console.log("not nayed");
           $("#{{blog.id}}_nay").css("color","black")
           $("#{{blog.id}}_nay").click(nay)
         </script>
         {% endif %}



</div>
  <div class="col-11" style="margin-top:5px;">
    <p style="font-size:0.9em;">{{blog.content|safe|truncatechars_html:450}}</p>

  </div>

</div>

<div class="row">
  <div class="col-3">
        <span class="images">
          {% if blog.blog_images.count < 4 %}
          {% for image in blog.blog_images.all %}
          <img class="post-images"src="{{image.img.url}}" alt="no image">
          {% endfor %}
          {% else %}
          {% for image in blog.blog_images.all|slice:':3' %}
          <img class="post-images"src="{{image.img.url}}" alt="no image">
          {% endfor %}
          <img class="post-images" src="{% static "css/plus_3.jpg" %}" alt="">
          {% endif %}
        </span>
  </div>
  <div class="col-6">
  </div>
  <div class="col-3">
    <a href="{% url 'blogs:details' pk=blog.pk %}" class="btn  btn-light">Read more</a>

  </div>
</div>

  </div>
</div>

web_project/blogs/templates/blogs/explore.html
{% extends "blogs/blog_base.html" %}
{% load static %}
{# <link rel="stylesheet" href="{% static "css/home.css" %}"> #}
{% block color %}
  <link rel="stylesheet" href="{% static "css/grey.css" %}">
{% endblock %}

{% block content %}

<body >

<div class="container">
  <center><h5 style="color:#28a745">Misc Blogs</h5></center>
</div>




<div class="container">
 <div class="row">

  <div class="col-md-8 col-sm-12 "style="margin-top:3vh;">

    {% for blog in blog_list %}
      {% include "blogs/_blog.html" %}
    {% endfor %}

  </div>

<div class="col-md-4 col-sm-0" >
  <div class="" style="margin-top:3vh;" id="userspace" >

    <div class="card" style="height: 60vh; width:18rem">
      <div class="card-body">
        {% if user.uer.profile_pic %}

        <img src="{{user.uer.profile_pic.url}}" class="userimage my-3" alt="">
        {% else %}
        <img src="{% static "css/uicon.png" %}" class="userimage my-3" alt="">
        {% endif %}
        <h5 class="card-title" style="text-align:center;">{{user.first_name}} {{user.last_name}}</h5>
        <br>

        <h5  style="text-align:center;" >BIO</h5>
        <p class="card-text">{{user.uer.bio}}</p>

        <h5  style="text-align:center;" >Joined At</h5>
        <p class="card-text" style="text-align:center;">{{user.date_joined|date:"d b Y"}}</p>

        <a href="{% url 'blogs:uerblogs' username=user.username %}" class="btn btn-outline-success mr-5">Blogs</a>
        <a href="{% url 'accounts:update' pk=user.id %}" class="btn btn-outline-success">Settings</a>
      </div>
</div>
</div>

</div>

</div>
</div>


<script type="text/javascript">

window.onscroll = function() {myFunction()};

var header = document.getElementById("userspace");
var sticky = header.offsetTop;

function myFunction() {
  if (window.pageYOffset > 400) {
    header.classList.add("sticky");
  } else {
    header.classList.remove("sticky");
  }
}


</script>
</body>

{% endblock %}

web_project/blogs/templates/blogs/home.html
{% extends "blogs/blog_base.html" %}
{% load static %}
{# <link rel="stylesheet" href="{% static "css/home.css" %}"> #}
{% block color %}
  <link rel="stylesheet" href="{% static "css/grey.css" %}">
{% endblock %}

{% block content %}

<body>
</body>

<div class="container">
  <h5 style="color :#03a87c;">Popular on U :</h5>
  <div class="row">
    {% for blog in trending|slice:':4'  %}
    <div class="col-md-3">
    <div class="mycard card" style="width: 100%;  ">
      <div class="card-body">
        <h5 class="card-title" style="font-size:1em;">{{blog.title|truncatechars_html:25}}</h5>
        <h6 class="card-subtitle mb-2" style="font-size:0.7em;opacity:0.7;" >{{blog.time_written|timesince}}</h6>
        <p style="font-size:0.7em;" class="card-text">{{blog.content|striptags|safe|truncatechars_html:60}}</p>
        <a style="  margin-bottom:20px; color:white; "href="{% url 'blogs:details' pk=blog.pk %}" class="card-link">See more</a>

      </div>

    </div>
    </div>
    {% endfor %}
 </div>
</div>




<div class="container">
 <div class="row">

  <div class="col-md-8 col-sm-12 "style="margin-top:3vh;">

    {% for blog in blog_list %}
      {% include "blogs/_blog.html" %}
    {% endfor %}

  </div>

<div class="col-md-4 col-sm-0" >
  <div class="" style="margin-top:3vh;" id="userspace" >

    <div class="card" style="height: 50rem; width:18rem; ">
      <div class="card-body" style="">
        {% if user.uer.profile_pic %}
        <img src="{{user.uer.profile_pic.url}}" class="userimage my-3" alt="">
        {% else %}
        <img src="{% static "css/uicon.png" %}" class="userimage my-3" alt="">
        {% endif %}
        <h5 class="card-title" style="text-align:center;">{{user.first_name}} {{user.last_name}}</h5>
        <br>

        <h5  style="text-align:center;" >BIO</h5>
        <p class="card-text">{{user.uer.bio}}</p>

        <h5  style="text-align:center;" >Joined At</h5>
        <p class="card-text" style="text-align:center;">{{user.date_joined|date:"d b Y"}}</p>

        <a href="{% url 'blogs:uerblogs' username=user.username %}" class="btn btn-outline-success mr-5">Blogs</a>
        <a href="{% url 'accounts:update' pk=user.uer.id %}" class="btn btn-outline-success">Settings</a>

        <a onclick="topFunction()" id="myBtn" title="Go to top">Top</a>

        <style media="screen">
          #myBtn {

  position: fixed; /* Fixed/sticky position */
  bottom: 20px; /* Place the button at the bottom of the page */
  right: 30px; /* Place the button 30px from the right */
  z-index: 99; /* Make sure it does not overlap */
  border: none; /* Remove borders */
  outline: none; /* Remove outline */
  background-color: grey; /* Set a background color */
  color: white; /* Text color */
  cursor: pointer; /* Add a mouse pointer on hover */
  padding: 15px; /* Some padding */
  border-radius: 10px; /* Rounded corners */
  font-size: 18px; /* Increase font size */
}

#myBtn:hover {
  background-color: #555; /* Add a dark-grey background on hover */
}

        </style>

        <script type="text/javascript">
          window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    document.getElementById("myBtn").style.display = "block";
  } else {
    document.getElementById("myBtn").style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0; // For Safari
  document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}
        </script>

      </div>
</div>
</div>

</div>

</div>
</div>


<script type="text/javascript">

window.onscroll = function() {myFunction()};

var header = document.getElementById("userspace");
var sticky = header.offsetTop;

function myFunction() {
  if (window.pageYOffset > 250) {
    header.classList.add("sticky");
  } else {
    header.classList.remove("sticky");
  }
}


</script>
</body>

{% endblock %}

web_project/blogs/templates/blogs/test.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form action="{% url 'blogs:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{form}}
      <input type="file" accept="image/*" name="image" value="">
      <input type="submit" name="" value="yalla">
    </form>
  </body>
</html>